fos_rest:
    param_fetcher_listener: force
    body_listener: true
    allowed_methods_listener: true
    body_converter:
        enabled: true
        validate: true
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
        view_response_listener: 'force'
        formats:
            xml:  false
            json: true
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: json }
